### ISSUE TITLE
HTTP/3 requirement

### ISSUE THREAD

**Issue by martinthomson** [bemasc/access-services#4]
This is a bit much.  Unless a specific version is necessary for specific reasons, specification should use the generic HTTP (RFC 9110).  In this case, the request is being made as a one-off.  That should be enough to use HTTP/1.1 even.

**Comment by bemasc** [comment]
HTTP/3 is specifically required because we need to be able to fetch the config via the proxy, and the proxy is only required to offer CONNECT-UDP.  To remove the HTTP/3 requirement on the target, we would need to add a "legacy CONNECT" requirement on the proxy.  This is not appealing for a few reasons:
* In a world where HTTP/3 is common, it's more complexity overall.
* "Legacy CONNECT" is not currently representable in the Access Description JSON.  We could add it, but ideally I would prefer to define a CONNECT-TCP that is nicely parallel to CONNECT-UDP.

I've added a brief rationale for this requirement to the text.

**Comment by martinthomson** [comment]
I disagree with that rationale, but it's your draft.

**Comment by bemasc** [comment]
OK, good to know.  I think that requiring HTTP/3 at the target amounts to less implementation work (and less specification text) than requiring Legacy CONNECT at the proxy, but I'm happy to flip that requirement if the consensus tilts the other way.
